DROP TABLE IF EXISTS measurements;
CREATE TABLE IF NOT EXISTS measurements (
    id INTEGER PRIMARY KEY,
    pm1 DECIMAL(6,2) DEFAULT 0,
    pm25 DECIMAL(6,2) DEFAULT 0,
    pm4 DECIMAL(6,2) DEFAULT 0,
    pm10 DECIMAL(6,2) DEFAULT 0,
    h DECIMAL(6,2) DEFAULT 0,
    t DECIMAL(6,2) DEFAULT 0,
    voc DECIMAL(6,2) DEFAULT 0,
    nox DECIMAL(6,2) DEFAULT 0,
    dateTime DATETIME
);
DROP TABLE IF EXISTS measurements_ARSO;
CREATE TABLE IF NOT EXISTS measurements_ARSO (
    id INTEGER PRIMARY KEY,
    merilno_mesto VARCHAR DEFAULT 0,
    datum_od DATETIME,
    datum_do DATETIME,
    so2 DECIMAL(6,2) DEFAULT 0,
    co DECIMAL(6,2) DEFAULT 0,
    o3 DECIMAL(6,2) DEFAULT 0,
    no2 DECIMAL(6,2) DEFAULT 0,
    pm10 DECIMAL(6,2) DEFAULT 0,
    pm25 DECIMAL(6,2) DEFAULT 0,
    benzen DECIMAL(6,2) DEFAULT 0,
    measurements_id INTEGER 
    FOREIGN KEY (measurements_id) REFERENCES measurements(id)
);