CREATE TABLE IF NOT EXISTS measurements (
  id INTEGER PRIMARY KEY,
  pm1 DECIMAL(6,2) DEFAULT 0,
  pm25 DECIMAL(6,2) DEFAULT 0,
  pm4 DECIMAL(6,2) DEFAULT 0,
  pm10 DECIMAL(6,2) DEFAULT 0,
  h DECIMAL(6,2) DEFAULT 0,
  t DECIMAL(6,2) DEFAULT 0,
  voc DECIMAL(6,2) DEFAULT 0,
  nox DECIMAL(6,2) DEFAULT 0,
  dateTime DATETIME
);